# @package _global_
defaults:
  - /train_p2n_state_gate_new
  - _self_

name: train_p2n_state_gate_new_convnext_nano_libero10
_target_: oat.workspace.train_p2n_new_convnext.TrainP2NNewWorkspace

policy:
  _target_: oat.policy.p2n_new_convnext.P2NStateGateNewPolicy
  obs_encoder_type: convnextv2_tokens
  expected_action_tokens: 8
  dino_path: null
  dino_revision: null
  tokenizer_checkpoint: /workspace/models/libero10-oat-so3aug/547243abb8e93752589ff674121bf129eb7327d773c72818c27ed3b9aebb3325/ep-4330_mse-0.001.ckpt
  convnext_model_name: convnextv2_nano.fcmae_ft_in22k_in1k
  convnext_path: /workspace/models/convnextv2_nano.fcmae_ft_in22k_in1k/aacb23b94d2adf0b206df6c8a75798b672183d6d
  convnext_revision: aacb23b94d2adf0b206df6c8a75798b672183d6d
  convnext_frozen: true
  vision_image_size: 224
  vision_feature_stages: [2, 3]
  visual_resampler_dim: 256
  visual_resampler_heads: 4
  visual_resampler_ffn_dim: 768

training:
  num_epochs: 251
  rollout_every: 100

task:
  policy:
    lazy_eval: false
    env_runner:
      _target_: oat.env_runner.p2n_new_convnext_libero10_runner.P2NStateGateNewLiberoRunner

logging:
  project: p2n_new_libero10
  name: ${now:%Y%m%d.%H%M%S}_${variant}_convnext_nano_libero10_seed${seed}
  tags: ['${variant}', 'libero10', 'convnextv2_nano']
  group: ${variant}_convnext_nano_libero10

hydra:
  run:
    dir: output/training/${variant}_convnext_nano_libero10_${now:%Y%m%d_%H%M%S}_seed${seed}
